services:
  server:
    build:
      context: server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_HOST=db
      - SECRET_KEY=/run/secrets/secret-key
      
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
  client:
    build: ./client/my-app
    ports:
      - 3000:3000
    volumes:
      - ./client/my-app:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - server
  db:
    build: 
      context: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=feedback_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  secret-key:
    file: server/jwt.txt
  db-password:
    file: db/password.txt